### ISSUE TITLE
torch problem

### ISSUE THREAD

**Issue by sistar2020** [SeulLee05/GEAM#1]
I installed GEAM with python 3.10 and cuda 11.7 on Ubuntu 22.4 because there was an error when tried with python 3.7 as described in README.

When I tried to run the following command, I got the following error:

```
$ python run.py -g 0 -t parp1 -m ckpt/parp1.pt -v data/parp1.txt
Namespace(gpu_id=0, seed=0, target='parp1', vocab_path='data/parp1.txt', num_mols=3000, batch_size=256, start_steps=4000, update_after=3000, update_every=256, emb_size=64, num_layer=3, tau=0.1, target_entropy=1.0, init_alpha=1.0, init_pi_lr=0.0001, init_q_lr=0.0001, init_alpha_lr=0.0005, alpha_max=20.0, alpha_min=0.05, population_size=100, mutation_rate=0.1, gib_path='ckpt/parp1.pt', max_vocab_update=50, max_vocab_size=1000)
Docking tmp dir: tmp/tmp0
results/2024-07-03-16-50-49_parp1_0.csv
 10%|█████████▊                                                                                          | 296/3000 [04:34<43:23,  1.04it/s]Traceback (most recent call last):
  File "/GEAM/run.py", line 72, in <module>
    main()
  File "/GEAM/run.py", line 67, in main
    sac.run()
  File "/GEAM/model/sac.py", line 485, in run
    self.update(data=batch)
  File "/GEAM/model/sac.py", line 348, in update
    loss_q.backward()
  File "/anaconda/envs/geam/lib/python3.10/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/anaconda/envs/geam/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [4466, 128]], which is output 0 of ReluBackward0, is at version 1; expected version 0 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!
 10%|█████████▊                                                                                          | 296/3000 [04:34<41:51,  1.08it/s]
tmp/tmp0 removed
```

I hope the authors will pay attention to this issue and take appropriate actions.
Here are my conda environments:

```
$ lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy

$ conda --version
conda 23.11.0

$ conda list
# packages in environment at /anaconda/envs/geam:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
aiohttp                   3.9.5                    pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
async-timeout             4.0.3                    pypi_0    pypi
attrs                     23.2.0                   pypi_0    pypi
blas                      1.0                         mkl
bottleneck                1.3.7           py310ha9d4c09_0
brotli                    1.0.9                h5eee18b_8
brotli-bin                1.0.9                h5eee18b_8
brotli-python             1.0.9           py310h6a678d5_8
bzip2                     1.0.8                h5eee18b_6
ca-certificates           2024.3.11            h06a4308_0
cairo                     1.18.0               h3faef2a_0    conda-forge
certifi                   2024.6.2        py310h06a4308_0
charset-normalizer        2.0.4              pyhd3eb1b0_0
cloudpickle               1.2.2                    pypi_0    pypi
contourpy                 1.2.0           py310hdb19cb5_0
cuda-cudart               11.7.99                       0    nvidia
cuda-cupti                11.7.101                      0    nvidia
cuda-libraries            11.7.1                        0    nvidia
cuda-nvrtc                11.7.99                       0    nvidia
cuda-nvtx                 11.7.91                       0    nvidia
cuda-runtime              11.7.1                        0    nvidia
cudatoolkit               11.7.1              h4bc3d14_13    conda-forge
cycler                    0.11.0             pyhd3eb1b0_0
dgl-cuda11.7              0.9.1post1              py310_0    dglteam
expat                     2.6.2                h6a678d5_0
ffmpeg                    4.3                  hf484d3e_0    pytorch
filelock                  3.13.1          py310h06a4308_0
font-ttf-dejavu-sans-mono 2.37                 hd3eb1b0_0
font-ttf-inconsolata      2.001                hcb22688_0
font-ttf-source-code-pro  2.030                hd3eb1b0_0
font-ttf-ubuntu           0.83                 h8b1ccd4_0
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-anaconda            1                    h8fa9717_0
fonts-conda-ecosystem     1                    hd3eb1b0_0
fonttools                 4.51.0          py310h5eee18b_0
freetype                  2.12.1               h4a9f257_0
frozenlist                1.4.1                    pypi_0    pypi
fsspec                    2024.6.1                 pypi_0    pypi
glib                      2.78.4               h6a678d5_0
glib-tools                2.78.4               h6a678d5_0
gmp                       6.2.1                h295c915_3
gmpy2                     2.1.2           py310heeb90bb_0
gnutls                    3.6.15               he1e5248_0
greenlet                  3.0.1           py310h6a678d5_0
gym                       0.13.0                   pypi_0    pypi
gym-notices               0.0.8                    pypi_0    pypi
icu                       73.2                 h59595ed_0    conda-forge
idna                      3.7             py310h06a4308_0
intel-openmp              2023.1.0         hdb19cb5_46306
jinja2                    3.1.4           py310h06a4308_0
joblib                    1.4.2                    pypi_0    pypi
jpeg                      9e                   h5eee18b_1
kiwisolver                1.4.4           py310h6a678d5_0
lame                      3.100                h7b6447c_0
lcms2                     2.12                 h3be6417_0
ld_impl_linux-64          2.38                 h1181459_1
lerc                      3.0                  h295c915_0
libboost                  1.84.0               h8013b2b_2    conda-forge
libboost-python           1.84.0          py310he6ccd79_3    conda-forge
libbrotlicommon           1.0.9                h5eee18b_8
libbrotlidec              1.0.9                h5eee18b_8
libbrotlienc              1.0.9                h5eee18b_8
libcublas                 11.10.3.66                    0    nvidia
libcufft                  10.7.2.124           h4fbf590_0    nvidia
libcufile                 1.9.1.3                       0    nvidia
libcurand                 10.3.5.147                    0    nvidia
libcusolver               11.4.0.1                      0    nvidia
libcusparse               11.7.4.91                     0    nvidia
libdeflate                1.17                 h5eee18b_1
libffi                    3.4.4                h6a678d5_1
libgcc-ng                 14.1.0               h77fa898_0    conda-forge
libgfortran-ng            11.2.0               h00389a5_1
libgfortran5              11.2.0               h1234567_1
libglib                   2.78.4               hdc74915_0
libgomp                   14.1.0               h77fa898_0    conda-forge
libiconv                  1.16                 h5eee18b_3
libidn2                   2.3.4                h5eee18b_0
libnpp                    11.7.4.75                     0    nvidia
libnsl                    2.0.0                h5eee18b_0
libnvjpeg                 11.8.0.2                      0    nvidia
libopenblas               0.3.21               h043d6bf_0
libpng                    1.6.39               h5eee18b_0
libsqlite                 3.46.0               hde9e2c9_0    conda-forge
libstdcxx-ng              14.1.0               hc0a3c3a_0    conda-forge
libtasn1                  4.19.0               h5eee18b_0
libtiff                   4.5.1                h6a678d5_0
libunistring              0.9.10               h27cfd23_0
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp-base              1.3.2                h5eee18b_0
libxcb                    1.15                 h7f8727e_0
libxml2                   2.13.1               hfdd30dd_0
libzlib                   1.2.13               h4ab18f5_6    conda-forge
lz4-c                     1.9.4                h6a678d5_1
markupsafe                2.1.3           py310h5eee18b_0
matplotlib-base           3.8.4           py310h1128e8f_0
mkl                       2023.1.0         h213fc3f_46344
mkl-service               2.4.0           py310h5eee18b_1
mkl_fft                   1.3.8           py310h5eee18b_0
mkl_random                1.2.4           py310hdb19cb5_0
more-itertools            10.3.0                   pypi_0    pypi
mpc                       1.1.0                h10f8cd9_1
mpfr                      4.0.2                hb69a4c5_1
mpmath                    1.3.0           py310h06a4308_0
multidict                 6.0.5                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0
nettle                    3.7.3                hbbd107a_1
networkx                  3.2.1           py310h06a4308_0
numexpr                   2.8.7           py310h85018f9_0
numpy                     1.26.4          py310h5f9d8c6_0
numpy-base                1.26.4          py310hb5e798b_0
openbabel                 3.1.1           py310hbff9852_9    conda-forge
openh264                  2.1.1                h4ff587b_0
openjpeg                  2.4.0                h9ca470c_1
openssl                   3.0.14               h5eee18b_0
packaging                 23.2            py310h06a4308_0
pandas                    2.2.2           py310h6a678d5_0
pcre2                     10.42                hebb0a14_1
pillow                    10.3.0          py310h5eee18b_0
pip                       24.0            py310h06a4308_0
pixman                    0.43.2               h59595ed_0    conda-forge
psutil                    5.9.0           py310h5eee18b_0
pybind11-abi              4                    hd3eb1b0_1
pycairo                   1.23.0          py310hd1222b9_0
pyglet                    2.0.15                   pypi_0    pypi
pyparsing                 3.0.9           py310h06a4308_0
pysocks                   1.7.1           py310h06a4308_0
python                    3.10.9          he550d4f_0_cpython    conda-forge
python-dateutil           2.9.0post0      py310h06a4308_2
python-tzdata             2023.3             pyhd3eb1b0_0
python_abi                3.10                    4_cp310    conda-forge
pytorch                   2.0.1           py3.10_cuda11.7_cudnn8.5.0_0    pytorch
pytorch-cuda              11.7                 h778d358_5    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2024.1          py310h06a4308_0
rdkit                     2024.03.4       py310h6f17f40_0    conda-forge
readline                  8.2                  h5eee18b_0
reportlab                 3.5.67          py310h0edfc0f_1
requests                  2.32.2          py310h06a4308_0
scikit-learn              1.5.0                    pypi_0    pypi
scipy                     1.13.1          py310h5f9d8c6_0
setuptools                69.5.1          py310h06a4308_0
six                       1.16.0             pyhd3eb1b0_1
sqlalchemy                2.0.30          py310h5eee18b_0
sqlite                    3.45.3               h5eee18b_0
sympy                     1.12            py310h06a4308_0
tbb                       2021.8.0             hdb19cb5_0
threadpoolctl             3.5.0                    pypi_0    pypi
tk                        8.6.14               h39e8969_0
torch-cluster             1.6.3                    pypi_0    pypi
torch-geometric           2.5.3                    pypi_0    pypi
torch-scatter             2.1.2                    pypi_0    pypi
torch-sparse              0.6.18                   pypi_0    pypi
torchaudio                2.0.2               py310_cu117    pytorch
torchtriton               2.0.0                     py310    pytorch
torchvision               0.15.2              py310_cu117    pytorch
tqdm                      4.66.4          py310h2f386ee_0
typing-extensions         4.11.0          py310h06a4308_0
typing_extensions         4.11.0          py310h06a4308_0
tzdata                    2024a                h04d1e81_0
unicodedata2              15.1.0          py310h5eee18b_0
urllib3                   2.2.2           py310h06a4308_0
wheel                     0.43.0          py310h06a4308_0
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.1.1                hd590300_0    conda-forge
xorg-libsm                1.2.4                h7391055_0    conda-forge
xorg-libx11               1.8.9                h8ee46fc_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxrender           0.9.11               hd590300_0    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xproto               7.0.31            h27cfd23_1007
xz                        5.4.6                h5eee18b_1
yarl                      1.9.4                    pypi_0    pypi
zlib                      1.2.13               h4ab18f5_6    conda-forge
zstd                      1.5.5                hc292b87_2

$ pip list
Package            Version
------------------ -----------
aiohttp            3.9.5
aiosignal          1.3.1
async-timeout      4.0.3
attrs              23.2.0
Bottleneck         1.3.7
Brotli             1.0.9
certifi            2024.6.2
charset-normalizer 2.0.4
cloudpickle        1.2.2
contourpy          1.2.0
cycler             0.11.0
dgl                0.9.1.post1
filelock           3.13.1
fonttools          4.51.0
frozenlist         1.4.1
fsspec             2024.6.1
gmpy2              2.1.2
greenlet           3.0.1
gym                0.13.0
gym-notices        0.0.8
idna               3.7
Jinja2             3.1.4
joblib             1.4.2
kiwisolver         1.4.4
MarkupSafe         2.1.3
matplotlib         3.8.4
mkl-fft            1.3.8
mkl-random         1.2.4
mkl-service        2.4.0
more-itertools     10.3.0
mpmath             1.3.0
multidict          6.0.5
networkx           3.2.1
numexpr            2.8.7
numpy              1.26.4
packaging          23.2
pandas             2.2.2
pillow             10.3.0
pip                24.0
psutil             5.9.0
pycairo            1.23.0
pyglet             2.0.15
pyparsing          3.0.9
PySocks            1.7.1
python-dateutil    2.9.0.post0
pytz               2024.1
rdkit              2024.3.4
reportlab          3.5.67
requests           2.32.2
scikit-learn       1.5.0
scipion-installer  1.0.16
scipy              1.13.1
setuptools         69.5.1
six                1.16.0
SQLAlchemy         2.0.30
sympy              1.12
threadpoolctl      3.5.0
torch              2.0.1
torch_cluster      1.6.3
torch_geometric    2.5.3
torch_scatter      2.1.2
torch_sparse       0.6.18
torchaudio         2.0.2
torchvision        0.15.2
tqdm               4.66.4
triton             2.0.0
typing_extensions  4.11.0
tzdata             2023.3
unicodedata2       15.1.0
urllib3            2.2.2
wheel              0.43.0
yarl               1.9.4
```

**Comment by SeulLee05** [comment]
Hello, thank you for your interest in our work.
I could not reproduce the error you've got.
It also doesn't appear to be a consistent error since it happened in the middle of the sampling.
However, based on the error message, it seems like it would be solved by not using in-place operations.
Can you try changing line 50 of `ac.py` to `h += h_in` -> `h = h + h_in`?

**Comment by SeulLee05** [comment]
Hello, thank you for your interest in our work.
I could not reproduce the error you received.
It also doesn't appear to be a consistent error since it happened in the middle of the sampling.
However, based on the error message, it seems like it would be solved by not using in-place operations.
Can you try changing line 50 of `ac.py` to `h += h_in` -> `h = h + h_in`?

**Comment by sistar2020** [comment]
OK. After fixing the code, it worked fine.
Thanks.

**Comment by Manjubn777** [comment]
I made this change, but it has significantly slowed down my computation. I am generating 50,000 compounds, and processing just 5,000 already took over 16 hours. Is there a more efficient way to speed this up?
 
1. h = h + h_in 
2. h = h.clone() 
   h += h_in  

Both take a similar amount of time. I would appreciate your prompt reply, thanks!
